### ISSUE TITLE
atom leak

### ISSUE THREAD

**Issue by karlseguin** [AlexKovalevych/exoffice#18]
Doesn't the String.to_atom on the path in the CSV parser make it likely that the code will leak atoms?  I was going to use this to parse CSV uploads through Plug, but those file names are randomly generated by plug. Why even give that Agent a name?

**Comment by rockneurotiko** [comment]
Yeah, you are totally right. I think the reason is to avoid opening more than once the same file at the same time, I don't really know why because the OS support reading from many processes at the same time.

I think that it makes sense to remove it, but if there are some use-case, we could just add an option to "disable" the naming for services that need to read tons of files, so there are no atom leaks problem.

**Comment by AlexKovalevych** [comment]
Well, named agents allow to prevent opening the same file twice, but comparing to atoms leak problem i think we can get rid of this check, so the client should handle such case himself (if needed).
